### ISSUE TITLE
get_random_data

### ISSUE THREAD

**Issue by BugOOM** [bubbliiiing/yolov5-v6.1-pytorch#10]
这个函数有几率触发bug，就是在最后的if len(box)>0那里
![image](https://user-images.githubusercontent.com/34702180/203802352-a1082d2c-2c3d-4fcf-9fbb-ffe99d733871.png)
正常的是这样的
![image](https://user-images.githubusercontent.com/34702180/203802431-9a6d1b7d-f8d1-44ff-b903-54538dc76d8a.png)
放到这里就行了
if flip and len(box) > 0:
            image = image.transpose(Image.FLIP_LEFT_RIGHT)
            box[:, [0, 2]] = iw - box[:, [2, 0]]

**Comment by bubbliiiing** [comment]
0 0
